# === configs/contrastive_learning.yaml ===
# Contrastive Learning Transformer settings

model:
  name: 'ContrastiveTransformer'
  encoding_dim: 10
  d_model: 128
  batch_size: 32
  epochs: 50
  learning_rate: 0.0001
  num_heads: 4
  hidden_dim: 128  # Previously 'd_model', renamed for PyTorch compatibility
  num_layers: 4
  output_dim: 64  # Transformer output size
  loss_function: 'cross_entropy'  # Updated for PyTorch
  optimizer: 'adam'
  device: 'mps'  # Change to 'cpu' if no GPU is available
  seed: 42  # Random seed for reproducibility
  ff_dim: 256

  # Model Saving & Loading
  save_model: True
  save_model_path: 'saved_models/contrastive_learning.pt'
  load_model: False
  load_model_path: 'saved_models/contrastive_learning.pt'
