# === configs/default.yaml ===
# General settings

dataset:
  start_date: '2017-01-01'
  end_date: '2025-12-31'
  source: 'ClickHouse'
  size: 1  # Add dataset size parameter

model:
  default_model: 'autoencoder'